feat(utils): pre-push hook to verify Cargo.toml version matches git tag

diff --git a/utils/pre-push-hook b/utils/pre-push-hook
--- a/utils/pre-push-hook
+++ b/utils/pre-push-hook
@@ -31,12 +31,16 @@ unstash() {
     git stash pop --quiet
 }
 
+fail() {
+    echo -e "\n${RED}${BOLD}Checks failed. Aborting!${CLEAR}" 1>&2
+    exit 1
+}
+
 stash
 
 echo -e "${BOLD}Running git push checks ...${CLEAR}\n"
-if ! ./utils/run-checks; then
-    echo -e "\n${RED}${BOLD}Checks failed. Aborting!${CLEAR}" 1>&2
-    exit 1
-fi
+
+./utils/check-pkg-version || fail
+./utils/run-checks || fail
 
 exit 0
